//! Browser access is opt-in. CORS never substitutes for bearer authorization.
use anyhow::{bail, Context, Result};
use hyper::header::{
    HeaderValue, ACCESS_CONTROL_ALLOW_HEADERS, ACCESS_CONTROL_ALLOW_METHODS,
    ACCESS_CONTROL_ALLOW_ORIGIN, ACCESS_CONTROL_MAX_AGE, ACCESS_CONTROL_REQUEST_HEADERS,
    ACCESS_CONTROL_REQUEST_METHOD, ORIGIN, VARY,
};
use hyper::{HeaderMap, Response, Uri};
const ENV: &str = "RESPIRE_CORS_ALLOWED_ORIGINS";
#[derive(Clone, Default)]
pub(super) struct Cors {
    origins: Vec<HeaderValue>,
}
impl Cors {
    pub(super) fn from_env() -> Result<Self> {
        match std::env::var(ENV) {
            Ok(value) => Self::parse(&value),
            Err(std::env::VarError::NotPresent) => Ok(Self::default()),
            Err(std::env::VarError::NotUnicode(_)) => bail!("{ENV} is not valid UTF-8"),
        }
    }
    pub(super) fn parse(value: &str) -> Result<Self> {
        let mut origins = Vec::new();
        if !value.trim().is_empty() {
            for raw in value.split(',').map(str::trim) {
                validate_origin(raw).with_context(|| format!("invalid origin in {ENV}"))?;
                let origin = HeaderValue::from_str(raw)?;
                if !origins.contains(&origin) {
                    origins.push(origin);
                }
            }
        }
        Ok(Self { origins })
    }
    pub(super) fn allowed_origin(&self, headers: &HeaderMap) -> Option<HeaderValue> {
        // Multiple Origin headers and origin lists are never trusted.
        let mut values = headers.get_all(ORIGIN).iter();
        let origin = values.next()?;
        if values.next().is_none() && self.origins.contains(origin) {
            Some(origin.clone())
        } else {
            None
        }
    }
    /// Validate preflight without reading its body, authenticating, or queuing DB work.
    pub(super) fn preflight_status(&self, headers: &HeaderMap) -> u16 {
        if self.allowed_origin(headers).is_none() {
            return 403;
        }
        let methods = headers.get_all(ACCESS_CONTROL_REQUEST_METHOD);
        let mut methods = methods.iter();
        match (methods.next().and_then(|v| v.to_str().ok()), methods.next()) {
            (Some("GET" | "POST"), None) => {}
            _ => return 405,
        }
        for value in headers.get_all(ACCESS_CONTROL_REQUEST_HEADERS) {
            let Ok(value) = value.to_str() else {
                return 403;
            };
            if !value.split(',').all(|name| {
                let name = name.trim();
                name.eq_ignore_ascii_case("authorization")
                    || name.eq_ignore_ascii_case("content-type")
            }) {
                return 403;
            }
        }
        204
    }
    /// One outer decoration covers every HTTP response generated by the app.
    pub(super) fn decorate<B>(
        response: &mut Response<B>,
        origin: Option<HeaderValue>,
        preflight: bool,
    ) {
        let success = response.status() == 204;
        let headers = response.headers_mut();
        headers.append(VARY, HeaderValue::from_static("Origin"));
        if preflight {
            headers.append(
                VARY,
                HeaderValue::from_static(
                    "Access-Control-Request-Method, Access-Control-Request-Headers",
                ),
            );
        }
        if let Some(origin) = origin {
            headers.insert(ACCESS_CONTROL_ALLOW_ORIGIN, origin);
            if preflight && success {
                headers.insert(
                    ACCESS_CONTROL_ALLOW_METHODS,
                    HeaderValue::from_static("GET, POST"),
                );
                headers.insert(
                    ACCESS_CONTROL_ALLOW_HEADERS,
                    HeaderValue::from_static("Authorization, Content-Type"),
                );
                headers.insert(ACCESS_CONTROL_MAX_AGE, HeaderValue::from_static("300"));
            }
        }
    }
}
fn validate_origin(raw: &str) -> Result<()> {
    let uri: Uri = raw
        .parse()
        .context("expected a serialized HTTP(S) origin")?;
    let scheme = uri.scheme_str().context("origin needs a scheme")?;
    let authority = uri.authority().context("origin needs a host")?;
    let host = uri.host().context("origin needs a host")?;
    if !matches!(scheme, "http" | "https")
        || raw != format!("{scheme}://{authority}")
        || authority.as_str().contains(['@', '*'])
        || host.is_empty()
        || host != host.to_ascii_lowercase()
    {
        bail!("use an exact lowercase HTTP(S) origin without wildcard, userinfo, path, query or fragment");
    }
    // HTTP is useful for isolated local development, never for remote bearer tokens.
    let ip_host = host.trim_start_matches('[').trim_end_matches(']');
    let loopback = host == "localhost"
        || ip_host
            .parse::<std::net::IpAddr>()
            .is_ok_and(|ip| ip.is_loopback());
    if scheme == "http" && !loopback {
        bail!("remote origins require HTTPS; HTTP is allowed only for localhost/loopback");
    }
    // Uri can discard an invalid port from port(); inspect the authority suffix too.
    let suffix = &authority.as_str()[host.len()..];
    if !suffix.is_empty() {
        let port = suffix
            .strip_prefix(':')
            .context("invalid origin authority")?;
        if port.parse::<u16>().ok().filter(|port| *port != 0).is_none() {
            bail!("origin port must be 1..65535");
        }
    }
    Ok(())
}
#[cfg(test)]
mod tests {
    use super::*;
    use hyper::header::ACCESS_CONTROL_ALLOW_CREDENTIALS;
    #[test]
    fn origin_config_is_exact_and_secure() -> Result<()> {
        assert!(Cors::parse(" \t")?.origins.is_empty());
        assert_eq!(
            Cors::parse("https://dash.rsrs.rs, https://admin.rsrs.rs,https://dash.rsrs.rs")?
                .origins
                .len(),
            2
        );
        for valid in [
            "https://preview.example.pages.dev",
            "http://localhost:5173",
            "http://127.0.0.1:5173",
            "http://[::1]:5173",
        ] {
            Cors::parse(valid).with_context(|| valid.to_owned())?;
        }
        for invalid in [
            "*",
            "null",
            "https://*.pages.dev",
            "https://dash.rsrs.rs/",
            "https://dash.rsrs.rs/path",
            "https://dash.rsrs.rs?q=1",
            "https://dash.rsrs.rs#x",
            "https://user@dash.rsrs.rs",
            "http://dash.rsrs.rs",
            "https://DASH.rsrs.rs",
            "https://dash.rsrs.rs,",
            "https://dash.rsrs.rs:70000",
            "https://dash.rsrs.rs:0",
            "https://dash.rsrs.rs:abc",
        ] {
            assert!(Cors::parse(invalid).is_err(), "accepted {invalid}");
        }
        Ok(())
    }
    #[test]
    fn origins_are_not_suffix_matched_or_normalized() -> Result<()> {
        let cors = Cors::parse("https://dash.rsrs.rs")?;
        for raw in [
            "null",
            "https://dash.rsrs.rs.evil.test",
            "https://preview.pages.dev",
            "http://dash.rsrs.rs",
            "https://dash.rsrs.rs:443",
            "https://dash.rsrs.rs https://evil.test",
        ] {
            let mut headers = HeaderMap::new();
            headers.insert(ORIGIN, HeaderValue::from_str(raw)?);
            assert!(cors.allowed_origin(&headers).is_none());
        }
        let mut headers = HeaderMap::new();
        headers.insert(ORIGIN, HeaderValue::from_static("https://dash.rsrs.rs"));
        assert!(cors.allowed_origin(&headers).is_some());
        headers.append(ORIGIN, HeaderValue::from_static("https://dash.rsrs.rs"));
        assert!(cors.allowed_origin(&headers).is_none());
        Ok(())
    }
    #[test]
    fn preflight_rejects_unapproved_methods_and_headers() -> Result<()> {
        let cors = Cors::parse("https://dash.rsrs.rs")?;
        let mut headers = HeaderMap::new();
        assert_eq!(cors.preflight_status(&headers), 403);
        headers.insert(ORIGIN, HeaderValue::from_static("https://dash.rsrs.rs"));
        assert_eq!(cors.preflight_status(&headers), 405);
        headers.insert(
            ACCESS_CONTROL_REQUEST_METHOD,
            HeaderValue::from_static("POST"),
        );
        assert_eq!(cors.preflight_status(&headers), 204);
        headers.insert(
            ACCESS_CONTROL_REQUEST_HEADERS,
            HeaderValue::from_static("authorization, CONTENT-TYPE"),
        );
        assert_eq!(cors.preflight_status(&headers), 204);
        headers.append(
            ACCESS_CONTROL_REQUEST_HEADERS,
            HeaderValue::from_static("X-Api-Key"),
        );
        assert_eq!(cors.preflight_status(&headers), 403);
        headers.remove(ACCESS_CONTROL_REQUEST_HEADERS);
        headers.insert(
            ACCESS_CONTROL_REQUEST_METHOD,
            HeaderValue::from_static("DELETE"),
        );
        assert_eq!(cors.preflight_status(&headers), 405);
        headers.insert(
            ACCESS_CONTROL_REQUEST_METHOD,
            HeaderValue::from_static("GET"),
        );
        headers.append(
            ACCESS_CONTROL_REQUEST_METHOD,
            HeaderValue::from_static("GET"),
        );
        assert_eq!(cors.preflight_status(&headers), 405);
        Ok(())
    }
    #[test]
    fn decorate_preserves_vary_and_never_allows_cookies() -> Result<()> {
        for status in [200, 204, 400, 401, 403, 408, 413, 429, 500, 503] {
            let mut response = Response::builder()
                .status(status)
                .header(VARY, "Accept-Encoding")
                .body(())?;
            Cors::decorate(
                &mut response,
                Some(HeaderValue::from_static("https://dash.rsrs.rs")),
                status == 204,
            );
            assert_eq!(
                response.headers()[ACCESS_CONTROL_ALLOW_ORIGIN],
                "https://dash.rsrs.rs"
            );
            assert!(!response
                .headers()
                .contains_key(ACCESS_CONTROL_ALLOW_CREDENTIALS));
            assert!(response
                .headers()
                .get_all(VARY)
                .iter()
                .any(|v| v == "Accept-Encoding"));
            assert!(response
                .headers()
                .get_all(VARY)
                .iter()
                .any(|v| v == "Origin"));
        }
        let mut denied = Response::new(());
        Cors::decorate(&mut denied, None, false);
        assert!(!denied.headers().contains_key(ACCESS_CONTROL_ALLOW_ORIGIN));
        assert_eq!(denied.headers()[VARY], "Origin");
        Ok(())
    }
}
