server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;

    location = /admin {
        default_type text/html;
        try_files /admin.html =404;
    }
    location = /dashboard {
        default_type text/html;
        try_files /admin.html =404;
    }
    location /dashboard/ {
        default_type text/html;
        try_files /admin.html =404;
    }

    location /zh/ {
        try_files $uri $uri/ /zh/index.html;
    }
    location / {
        try_files $uri $uri/ /index.html;
    }
}
